version: '3.8'

services:
  news-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    dns:
      - 8.8.8.8
      - 8.8.4.4
    
  # Development service with hot-reload
  news-app-dev:
    build:
      context: .
      target: build
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    volumes:
      - ./:/app
      - /app/node_modules
    command: npm run dev